import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xff100B20);
const kWhiteColor = Colors.white;
const kBlackColor = Colors.black87;
const kYellowColor = Color(0xffDDB130);
const kDisablesButtonColor = Color(0xffb1b2cb);
const kButtonColor = Color(0xffDDB130);
const kTextFieldHintColor = Color(0xff96A0B6);
Color kBorderColor = const Color(0x33FFFFFF);
Color kFilledColor = const Color(0x1AFFFFFF);
const kErrorColor = Colors.red;
const kWarningColor = Color(0xFFfeb700);
const kSuccessColor = Color(0xFF00c870);
const kHintColor = Colors.white60;
const kIconColor = Colors.white70;
const kRedColor = Colors.red;
const kFirstGradientFavorite = Color(0x26FFFFFF);
const kSecondGradientFavorite = Color(0x0DFFFFFF);
const kBlueColor = Color(0x4D2196F3);
const kFirstGradientBodyColor = Color(0xFF1B263B);
const kSecondGradientBodyColor = Color(0xFF0D1B2A);
